swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: localhost
basePath: /v1
schemes:
  - http
paths:
  /cidades:
    get:
      summary: Lista de cidades.
      description: Cidades cadastradas
      produces:
        - application/json
      responses:
        200:
          description: cidades
          schema:
            type: array
            items:
              $ref: '#/definitions/Cidade'
          
          
definitions:
   Cidade:
      type: "object"
      properties:
         nome:
          type: string
         estado: 
           type: "integer"
            
    